name: Release materials

on:
  push:
    tags:
      - "L*-v*"

jobs:
  release:
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: CUNI-NATUR-Biostatistics/CUNI-NATUR-Biostatistics.github.io/.github/workflows/release.yml@main
    secrets: inherit
